name: Backend Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # MongoDB service container
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
        
    - name: Set environment variables
      run: |
        echo "ENVIRONMENT=test" >> $GITHUB_ENV
        echo "MONGODB_URL=mongodb://localhost:27017/bluewhale_test" >> $GITHUB_ENV
        echo "CSRF_SECRET_KEY=test_csrf_secret_key" >> $GITHUB_ENV
        echo "JWT_SECRET_KEY=test_jwt_secret_key" >> $GITHUB_ENV
        
    - name: Run tests
      working-directory: ./backend
      run: |
        python -m pytest tests/ -v
        
    - name: Run MFA tests specifically
      working-directory: ./backend
      run: |
        python -m pytest tests/test_mfa.py -v
        
    - name: Generate coverage report
      working-directory: ./backend
      run: |
        python -m pytest tests/ --cov=app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        fail_ci_if_error: false
